name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1'

    - run: julia -e '
            using Pkg;
            Pkg.activate(".");
            Pkg.instantiate();
            using Franklin;
            optimize(
              prepath   = "adventure-time",
              clear     = true,
              prerender = false,
              minify    = false
            )'

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: __site
